### PR TITLE
Freetype Fonts

### PR DESCRIPTION
**Pull request by ACBob**
Before merging, we need:
 - [x] Font rendering, loading
 - [x] Support text modifiers (I.e newline, colours, etc.)\
    *We have newline and colours, but there seems to be more...*\
   EDIT: Turns out we were handling the colour codes incorrectly, lol!
 - [x] Full* (Most?) of the text rendering API re-implemented

*We don't need all of it, we remove parts of it.

### CODE REVIEW

**Comment by ACBob** [comment]
It may be worth also extending the rendertext, to allow for *italics* and **bold**. Although this may be better as a seperate PR.

**Comment by ACBob** [comment]
The only functions that need to be implemented are `text_visible(char, float, float, int)` and `text_posf(char, int, float, float, int)`.\
The current implementation also completely ignores the specified maxwidth.

We don't need reloadfonts, who wants to reload fonts? :trollface:

**Comment by yellowberryHN** [comment]
You're insane, I've been trying to get Freetype into Cube 2 for 6 months and I just couldn't figure it out. Top job!

**Comment by ACBob** [comment]
My implementation could do with some work*, but it does function!\
I'd be glad if it can be of some use :).

*Such as;
 * Not all the text drawing functions are implemented
 * We generate an OpenGL texture for each character, It could probably be connected into one atlas for more optimization
 * The textures are disconnected from the actual texture system, meaning they aren't properly destructed (Memory leak?)

**Comment by yellowberryHN** [comment]
Alas, there will always be some sorts of problems with something so hastily implemented, however now that it's functional, it's a lot easier to go about reworking the functional code instead of trying to abstract it from the beginning and confusing yourself.  I'll be implementing this into my fork, and I'll contribute back any fixes I may come up with as pull requests!

**Comment by yellowberryHN** [comment]
I just looked into what it'll take to implement some of the missing functions, spaghetti defines everywhere. 

EDIT: Cleaned up `text_visible()`, this is what came of it:
```cpp
int text_visible(const char *str, float hitx, float hity, int maxwidth)
{
    float y = 0, x = 0, scale = curfont->scale/float(curfont->defaulth);
    int i;
    for(i = 0; str[i]; i++)
    {
        int c = uchar(str[i]);
        if(c=='\t')      { x = TEXTTAB(x); if(y+FONTH > hity && x >= hitx) return i; }
        else if(c==' ')  { x += scale*curfont->defaultw; if(y+FONTH > hity && x >= hitx) return i; }
        else if(c=='\n') { if(y+FONTH > hity) return i; x = 0; y += FONTH; }
        else if(c=='\f') { if(str[i+1]) { i++; }}
        else if(curfont->chars.inrange(c-curfont->charoffset))
        {
            float cw = scale*curfont->chars[c-curfont->charoffset].advance;
            if(cw <= 0) continue;
            if(maxwidth != -1)
            {
                int j = i;
                float w = cw;
                for(; str[i+1]; i++)
                {
                    int c = uchar(str[i+1]);
                    if(c=='\f') { if(str[i+2]) i++; continue; }
                    if(i-j > 16) break;
                    if(!curfont->chars.inrange(c-curfont->charoffset)) break;
                    float cw = scale*curfont->chars[c-curfont->charoffset].advance;
                    if(cw <= 0 || w + cw > maxwidth) break;
                    w += cw;
                }
                if(x + w > maxwidth && j!=0) { if(y+FONTH > hity) return j-1; x = 0; y += FONTH; }
                for(; j <= i; j++)
                {
                    int c = uchar(str[j]);
                    if(c=='\f') { if(str[j+1]) { j++; }}
                    else { float cw = scale*curfont->chars[c-curfont->charoffset].advance; x += cw; if(y+FONTH > hity && x >= hitx) return j; }
                }
            }
            else
            { x += cw; if(y+FONTH > hity && x >= hitx) return i; }
        }
    }
    return i;
}
```

**Comment by ACBob** [comment]
Yeah, the cube 2 code has a beautiful license, but can be truly awful.\
I'm not sure where-abouts this function is used, nor what it does, But I'll assume it's functional and implement it.

**Pull request merged**
